Modules = [
    "github.com/erlangs/hexya-web"$$MODULEPATH$$
]
LogStdout = true
#LogFile = ""
#LogLevel = "info"
#Debug = false
#DataDir = ""

[DB]
Driver = "postgres"
Host = "127.0.0.1"
Port = 5432
User = "postgres"
Password = "postgres"
Name = "hexyaoth"

[Server]
#Languages = ["fr"]
#Interface = ""
Port = 8186
